### ISSUE TITLE
请问单位球面那个模型用的是哪个呢

### ISSUE THREAD

**Issue by Flame-shi** [imuncle/DSCM_Calib#6]
代码里有个get_unit_sphere_coordinate，看不太懂，请问有参考的论文或者理论吗

**Comment by Flame-shi** [comment]
另外代码投影模型中的参数b_ , c_是什么意思呢， 大佬发的cvpr论文里好像也没有这两个参数

**Comment by imuncle** [comment]
> 代码里有个get_unit_sphere_coordinate，看不太懂，请问有参考的论文或者理论吗

这个函数对应论文中的π^-1，即逆投影方程

> 另外代码投影模型中的参数b_ , c_是什么意思呢， 大佬发的cvpr论文里好像也没有这两个参数

这个确实没在论文中体现，我参考了Scaramuzza提出的相机模型的思想，将归一化平面和像素平面之间视为仿射变换，b和c是仿射变换的参数

Scaramuzza, A toolbox for easily calibrating omnidirectional cameras. 2006

**Comment by Flame-shi** [comment]
@imuncle 好的，十分感谢。还有个小问题请教下，为什么代码Reproject和Project操作的时候世界坐标系的点P的z坐标是默认设为1呢（例如 cv::Mat P = (cv::Mat_<double>(3, 1) << (j - chessboard_size), (i - chessboard_size), 1);），我尝试了下设置为其他值是明显错误

**Comment by imuncle** [comment]
@Liao-lin 这是2D点的齐次坐标，齐次坐标的最后一维是1

> 另外其实b_和c_对标定精度的提升几乎为0，可以忽略

**Comment by Flame-shi** [comment]
> @Liao-lin 这是2D点的齐次坐标，齐次坐标的最后一维是1
> @imuncle 

十分感谢大佬回复。现在看完了代码，剩一个疑惑点：
      代码里只在外参估计的时候，将世界点的z传入了opencv的外参估计函数solvePnPRansac中，而ceres非线性优化没有用到z坐标。我给棋盘格点赋予不同的z坐标的世界点，似乎对图片矫正效果没有影响，也就是说矫正的时候默认棋盘格角点在同一平面。那假设棋盘格本身有已知的高度差（非平面而是阶梯面），那是不是得先TSCM矫正再做下一步高度矫正，或先高度矫正再通过TSCM矫正，因为输入的棋盘格角点的z不影响TSCM鱼眼矫正过程

**Comment by imuncle** [comment]
棋盘格点的3D坐标是先验信息，是作为约束项参与优化，其值本身不能被优化。

棋盘格非平面的话，现有的矫正代码没法用，因此代码中的精细化角点就做不了了

**Comment by Flame-shi** [comment]
是的，是约束项，但是z没有作为先验信息传进去。谢谢大佬。
