### ISSUE TITLE
请问这个模型用于畸变较小的相机进行矫正时，误差较大是怎么回事

### ISSUE THREAD

**Issue by Flame-shi** [imuncle/DSCM_Calib#7]
请教下，使用一个畸变较小的鱼眼相机矫正时，四个角畸变比较明显是怎么回事呢，是这个模型参数初始化的问题吗，感觉看论文示意图，模型是兼容小畸变的相机的
这是畸变前的效果：
![image](https://github.com/imuncle/TSCM_Calib/assets/46985683/711269ea-20b9-4ef3-b98d-29f047a82654)
这是畸变矫正后的效果
![image](https://github.com/imuncle/TSCM_Calib/assets/46985683/cfaf036e-fd8e-46c8-9899-4ed70c9ca1fa)

**Comment by imuncle** [comment]
标定板图片采集了多少张，有没有把视野里每块区域都覆盖到

**Comment by Flame-shi** [comment]
你好，只采集了一张（场景需求是只拍一张，如上图），只需要矫正棋盘格范围内的视野。试了其他两款畸变较大的鱼眼相机是可以通过一张图正常矫正，矫正效果很好（也是如上图随便拍的），这款相机畸变小，反而无法正常矫正

**Comment by imuncle** [comment]
因为这个模型是为鱼眼相机设计的，相对于针孔相机多了三个参数，畸变小的话容易过拟合，或者说出现了Runge现象。比如用五阶曲线拟合一条呈线性分布的散点，如果点少的话，虽然拟合结果的误差很小，但在点集之外不一定与真正的趋势一致。

我建议如果是小畸变相机的话，把`xi`和`lambda`都置为0，并且不参与优化，也就是只保留`alpha`这一个参数。

修改`TS.h`：

```cpp
// 注释118-119行
// T d2 = ceres::sqrt(P[0]*P[0]+P[1]*P[1]+(P[2]+intrinsic_[4]*d1)*(P[2]+intrinsic_[4]*d1));
// T d3 = ceres::sqrt(P[0]*P[0]+P[1]*P[1]+(P[2]+intrinsic_[4]*d1+intrinsic_[5]*d2)*(P[2]+intrinsic_[4]*d1+intrinsic_[5]*d2));
// 修改第120行如下
T ksai = P[2]+intrinsic_[6]/(one-intrinsic_[6])*d1;
```

**Comment by Flame-shi** [comment]
谢谢大佬，解答很详细 ，十分感谢

**Comment by Flame-shi** [comment]
大佬好，之前因为别的事没去试修改的方案，今天尝试了一下，按博主的方法把xi和lambda都置为0且不参与优化，结果还是差不多，矫正效果和上图几乎一样。我查看了下参数，参与优化的时候其实xi和lamda的值都趋近于0了（0.002），所以置为0后效果也差不多。不知道这个是什么原因呢

**Comment by imuncle** [comment]
这样啊，方便的话可以把测试图片发我邮箱：big.uncle@foxmail.com，我试试

**Comment by imuncle** [comment]
我试了一下，看来这个模型的光路假设在小畸变相机上不适用，还是老实用回径向畸变和切向畸变吧 :(

**Comment by Flame-shi** [comment]
> 我试了一下，看来这个模型的光路假设在小畸变相机上不适用，还是老实用回径向畸变和切向畸变吧 :(

好的 感谢。看来只能用传统畸变模型看看
