### ISSUE TITLE
请教一下这个模型的近大远小缩放中心应该怎么算

### ISSUE THREAD

**Issue by Flame-shi** [imuncle/DSCM_Calib#8]
普通相机近大远小的缩放中心应该是相机中心，这个模型的缩放中心好像一直会随着物距变动，我使用物距15cm时候矫正好的图片与物距14cm矫正好的时候图片计算的缩放中心a，与物距13cm时候矫正好的图片与物距14cm矫正好的时候这两张图片计算的缩放中心b，并不一致，就算a点和b点反推到原来的未矫正图片中对应的点a1和b1也并非一致，相差几十像素， 请问这个缩放中心有好的推算方法吗或者有什么共性吗

**Comment by imuncle** [comment]
你的缩放中心是怎么计算的

**Comment by Flame-shi** [comment]
> 你的缩放中心是怎么计算的

相机在支架上，下面有个升降平台，升降平台有一对标记点，对比这两个标记点在升降前后的矫正后（无畸变）图片的位置，算出来对应缩放中心（简单的比例关系，两点上升后到缩放中心的距离与上升前到缩放中心的距离比例相同，解方程）。我猜测可能是计算的是外参做变换后矫正的图像的比例中心，所以导致问题，但是把P = Rt * P;这句注释了，以为会得到没做外参旋转平移变换的图像，结果图像没法矫正

**Comment by Flame-shi** [comment]
> > 你的缩放中心是怎么计算的
> 
> 相机在支架上，下面有个升降平台，升降平台有一对标记点，对比这两个标记点在升降前后的矫正后（无畸变）图片的位置，算出来对应缩放中心（简单的比例关系，两点上升后到缩放中心的距离与上升前到缩放中心的距离比例相同，解方程）。我猜测可能是计算的是外参做变换后矫正的图像的比例中心，所以导致问题，但是把P = Rt * P;这句注释了，以为会得到没做外参旋转平移变换的图像，结果图像没法矫正

矫正用的是undistort_chessboard这个函数

**Comment by Flame-shi** [comment]
> > 你的缩放中心是怎么计算的
> 
> 相机在支架上，下面有个升降平台，升降平台有一对标记点，对比这两个标记点在升降前后的矫正后（无畸变）图片的位置，算出来对应缩放中心（简单的比例关系，两点上升后到缩放中心的距离与上升前到缩放中心的距离比例相同，解方程）。我猜测可能是计算的是外参做变换后矫正的图像的比例中心，所以导致问题，但是把P = Rt * P;这句注释了，以为会得到没做外参旋转平移变换的图像，结果图像没法矫正

矫正用的是undistort_chessboard这个函数

**Comment by imuncle** [comment]
抱歉还是没太看懂。如果只是想去畸变的话，可以使用`undistort`这个函数，见[TS.cpp](https://github.com/imuncle/TSCM_Calib/blob/main/TS.cpp#L284)。

**Comment by Flame-shi** [comment]
> 抱歉还是没太看懂。如果只是想去畸变的话，可以使用`undistort`这个函数，见[TS.cpp](https://github.com/imuncle/TSCM_Calib/blob/main/TS.cpp#L284)。
不好意思确实描述不清晰，意思是只调整相机高度，棋盘格平面上有两个标记点，比如14cm和15cm物距下，使用undistort_chessboard矫正后的图片的标记点位置，计算的缩放中心，和15cm与16cm两张图计算的缩放中心不一样（可能确实也不好理解）
这个函数之前有用过 ，但是有个问题就是输入参数里的（double fx, double fy, double cx, double cy）如果使用标定得到的参数矫正显示效果可能很差，可能只看到一点视野，不同拍摄场景可能得自己调整一下手动调参

**Comment by Flame-shi** [comment]
已经解决了，感谢! 是机械设备问题，调整物距的设备有误差，物距改变的时候发生了微小旋转，导致缩放中心计算错误。
